### ISSUE TITLE
Μέθοδος μαύρο κουτί

### ISSUE THREAD

**Issue by efotos** [lalibi/aepp-presentation#1]
Καλησπέρα, ΚΑΤΑΠΛΗΚΤΙΚΗ ΔΟΥΛΕΙΑ. Το πρόβλημα είναι ότι ακόμη και με την τωρινή ανανέωση δεν μπορώ να εντοπίσω στις διαφένειες τη μέθοδο μαύρου κουτιού. Υπάρχει κάποιο θέμα ή το προσπέρασα κατά την αναζήτηση; Ευχαριστώ πολύ!

**Comment by lalibi** [comment]
Σε ευχαριστώ πολύ! Για να μπορεί να παίζει η παρουσίαση και offline κάνω λίγο aggressive caching (με service worker). Αυτό έχει σαν αποτέλεσμα να μην εμφανίζονται αμέσως οι αλλαγές, Συνήθως, αν κλείσεις το παράθυρο/tab και το ξαναανοίξεις, είναι οκ. Δοκίμασε το και πες μου.

**Comment by efotos** [comment]
Όλα κομπλέ! Στη διαφάνεια 346, άλλαξε στη δήλωση των μεταβλητών τη μεταβλητή "οφειλόμενο" σε "οφειλόμενο_ποσό" γιατί σωστά μου είπαν οι μαθητές μου ότι έχει και συντακτικό σφάλμα.
