### ISSUE TITLE
Διόρθωση σε κώδικα σε λυμένη άσκηση

### ISSUE THREAD

**Issue by SFilippidis** [lalibi/aepp-presentation#2]
Στην διαφάνεια 433 (όπως είναι με τη σημερινή μορφή των διαφανειών στο διαδίκτυο) οι μαθητές μου στο σχολείο πρόσεξαν ότι η τελευταία γραμμή πρέπει να είναι

ΓΡΑΨΕ ον_max

ΥΓ: συγχαρητήρια για την εξαιρετική δουλειά που έχεις κάνει συνάδελφε!

**Comment by lalibi** [comment]
Σε ευχαριστώ για τα καλά σου λόγια, διορθώθηκε.

Ευπρόσδεκτη οποιαδήποτε άλλη παρατήρηση / διόρθωση.

**Comment by SFilippidis** [comment]
1) Στην διαφάνεια **562** (όπως είναι με τη σημερινή μορφή των διαφανειών στο διαδίκτυο) οι μαθητές μου στο σχολείο πρόσεξαν ότι πριν ή μετά την γραμμή

max <- πλ_20[i]

πρέπει να μπει γραμμή

θ_max <- i

2) Στην διαφάνεια **564** (όπως είναι με τη σημερινή μορφή των διαφανειών στο διαδίκτυο) οι μαθητές μου στο σχολείο πρόσεξαν ότι στο τμήμα κώδικα

ΑΝ βρέθηκε ΤΟΤΕ
    max <- ΣΚΟΡ[θέση_i,**j**]
    θέση_j <- 1 

τη δεύτερη από τις γραμμές αυτές θέλει αλλαγή ως εξής:

max <- ΣΚΟΡ[θέση_i,**1**]
